# Generated by Django 4.0.3 on 2022-03-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
