# Generated by Django 4.0.3 on 2022-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AddField(
            model_name='petphoto',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
