# Generated by Django 4.0.3 on 2022-04-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_like_likes_petphoto_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='likes',
        ),
    ]
